### ISSUE TITLE
Can't pass 2FA with application specific password

### ISSUE THREAD

**Issue by rovkinmax** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#85]
I already create and add application specific password to this step. But I get error.
Full log here https://app.bitrise.io/build/1897b6874b55e2e4#?tab=log
```
Connected Apple Developer Portal Account found, exposing FASTLANE_SESSION env var
Session exported
Setup
fastlane version defined: latest-stable, installing...
$ gem "install" "fastlane" "--no-document"
$ rbenv "rehash"
$ fastlane "-v"
fastlane installation at path:
/Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/bin/fastlane
-----------------------------
fastlane 2.152.0
#######################################################################
# fastlane 2.162.0 is available. You are on 2.152.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
Setup took 273.556763 seconds to complete

Deploy
**Note:** if your password
contains special characters
and you experience problems, please
consider changing your password
to something with only
alphanumeric characters.
**Be advised**
that this step uses a well maintained, open source tool which
uses *undocumented and unsupported APIs* (because the current
iTunes Connect platform does not have a documented and supported API)
to perform the deployment.
This means that when the API changes
**this step might fail until the tool is updated**.
$ fastlane "deliver" "--username" "[REDACTED]" "--app_identifier" "[REDACTED]" "--team_id" "[REDACTED]" "--ipa" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/ipaOrPkg241275254/tmp.ipa" "--skip_screenshots" "--skip_metadata" "--force" "--platform" "ios"
[13:53:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:53:32]: Sending anonymous analytics information
[13:53:32]: Learn more at https://docs.fastlane.tools/#metrics
[13:53:32]: No personal or sensitive data is sent.
[13:53:32]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[13:53:32]: Login to App Store Connect ([REDACTED])
Two-factor Authentication (6 digits code) is enabled for account '[REDACTED]'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)
(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship_2fa_sms_default_phone_number)
Please enter the 6 digit code:

Looking for related GitHub issues on fastlane/fastlane...
➡️  [Swift] undefined method `each' for nil:NilClass - Cannot Create Group Within FastlaneSwiftRunner Project
    https://github.com/fastlane/fastlane/issues/15184 [open] 41 💬
    a week ago
➡️  [!] undefined method `[]' for #<Gem::NameTuple fastlane, 2.143.0, ruby> (NoMethodError)
    https://github.com/fastlane/fastlane/issues/16127 [open] 29 💬
    17 hours ago
➡️  undefined method `login' for Spaceship::Tunes:Module
    https://github.com/fastlane/fastlane/issues/15495 [closed] 7 💬
    13 Feb 2020
and 8 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60strip%27%20for%20nil%0ADid%20you%20mean%3F%20%20String&type=Issues&utf8=✓
🔗  You can ⌘ + double-click on links to open them directly in your browser.
#######################################################################
# fastlane 2.162.0 is available. You are on 2.152.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
/Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace': [!] undefined method `strip' for nil:NilClass (NoMethodError)
Did you mean?  String
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:873:in `get_line'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `ask'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:225:in `ask_for_2fa_code'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:159:in `handle_two_factor'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:495:in `send_shared_login_request'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:777:in `do_login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:385:in `login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:347:in `login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:30:in `login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:22:in `initialize'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/commands_generator.rb:80:in `new'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/commands_generator.rb:80:in `block (2 levels) in run'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/commands_generator.rb:183:in `run'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/bin/fastlane:23:in `<top (required)>'
	from /Users/vagrant/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	from /Users/vagrant/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
/Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace': undefined method `strip' for nil:NilClass (NoMethodError)
Did you mean?  String
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:873:in `get_line'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `ask'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:225:in `ask_for_2fa_code'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:159:in `handle_two_factor'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:495:in `send_shared_login_request'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:777:in `do_login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:385:in `login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:347:in `login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:30:in `login'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:22:in `initialize'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/commands_generator.rb:80:in `new'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/commands_generator.rb:80:in `block (2 levels) in run'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/commands_generator.rb:183:in `run'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/bin/fastlane:23:in `<top (required)>'
	from /Users/vagrant/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	from /Users/vagrant/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
If you have issues, use the latest prerelease version of fastlane.
Set the fastlane version input to "latest" to enable prerelease versions.
Deploy failed, error: exit status 1
```

**Comment by bitce** [comment]
Hi @rovkinmax! Can you enable Support User access for us in the Settings of the app?

**Comment by rovkinmax** [comment]
Hi @bitce! Done!

**Comment by bitce** [comment]
Thanks! Strangely, the URL the build leads to be appears to fail on this step, but with an entirely different output:

```
Failed to ensure Fastlane version, error: gem install command failed, output: ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies faraday (~> 0.12) and faraday (~> 1.0)
  Activated faraday-1.0.0
  which does not match conflicting dependency (~> 0.12)
  Conflicting dependency chains:
    fastlane (= 2.162.0), 2.162.0 activated, depends on
    faraday (~> 1.0), 1.0.0 activated
  versus:
    fastlane (= 2.162.0), 2.162.0 activated, depends on
    google-api-client (>= 0.37.0, < 0.39.0), 0.37.0 activated, depends on
    googleauth (~> 0.9), 0.9.0 activated, depends on
    faraday (~> 0.12)
  Gems matching faraday (~> 0.12):
    faraday-0.17.1, faraday-0.15.4, error: exit status 1
```

This error above, I think could be fixed by running `sudo gem update` in a Script step before this one.

**Comment by rovkinmax** [comment]
@bitce Sorry, you can see other build https://app.bitrise.io/build/244af220befc2a36#?tab=log
I tried set manually fastlane version in build at the topick

**Comment by mjones-droid** [comment]
Hey @rovkinmax! Sorry you're having issues. 

Please go in to your "Deploy to iTunes Connect" step. Under "Debug Options" you'll see a field for "fastlane version". Change that value from latest-stable to latest.

**Comment by victormihaita** [comment]
I have the same issue.. I was using fastlane directly with Bitrise for managing all my steps and it was breaking.. I decided to switch to Bitrise Steps instead and it seems that now is also failing on this deployment step...
Could you please help with this issue? I cannot release to AppStore at all because of this. Thanks

**Comment by rovkinmax** [comment]
@mjones-droid latest instead latest-stable not helps
https://app.bitrise.io/build/d53b193dc115cefe#?tab=log

**Comment by victormihaita** [comment]
I think also this issue is related to this.. https://discuss.bitrise.io/t/bitrise-repeatedly-asking-2factor-authentication-on-fastlane-actions/13992/7
It is a Fastlane issue for sure..

**Comment by mjones-droid** [comment]
I think @victormihaita may be correct. @rovkinmax, please try the [suggested workaround](https://discuss.bitrise.io/t/bitrise-repeatedly-asking-2factor-authentication-on-fastlane-actions/13992/7).

We do have the "Deploy to iTunes Connect - Application Loader" step, but it only uploads the binary file. It doesn't do any of the other updates (such as version notes).

**Comment by victormihaita** [comment]
@mjones-droid can you have a look at this? https://docs.fastlane.tools/app-store-connect-api/#use-return-value-and-pass-in-as-an-option 
I think this is the solution for the issue

**Comment by victormihaita** [comment]
I got this answer from Fastlane team: https://github.com/fastlane/fastlane/issues/17415#issuecomment-707328584

**Comment by sdeff** [comment]
I'm experiencing the same issue. Are there any updates yet?

**Comment by ilyakar** [comment]
Just created a new account and gave them the App Manager and Developer role for my app. This account has no 2FA enabled. Building the app on bitrise now with this account set up in the Deploy to iTunes Connect step. Let's see. Although, should work.

**Comment by mjones-droid** [comment]
I know this might seem obvious so I almost hate to ask it, but I want to make sure the bases are covered.

Did you connect your iTunes Connect account to Bitrise? If so, did you use the API connection or the session based auth?

**Comment by zdurlan** [comment]
I have the same issue. Did anyone manage to make it work? I cannot upload to Testflight, although the build passes without the upload-to-testflight workflow action.

**Comment by victormihaita** [comment]
you need to set an api_key: 
`api_key = app_store_connect_api_key(
    key_id: "xxxxx",
    issuer_id: "xxxxx"
    key_filepath: "./fastlane/AuthKey_xxx.p8"
)
`

and then you can use that key like this: 
`upload_to_testflight(api_key: api_key)`

more info here: [Fastlane-app_store_connect_api_key](https://docs.fastlane.tools/actions/app_store_connect_api_key/)

**Comment by knox** [comment]
It's a pitty that 2FA is still an issue! I'm pretty sure that all it takes is a _minor_ change in the existing bitrise step. It was requested in #37 in January 2018 for the first time but got closed without any solution. And there even is an pull request for it in #77 since December 2019 but nobody seems to care?

For me this works perfectly - but it can't be triggered by this bitrise step:
```
$ export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="my-app-specific-password"
$ fastlane "deliver" "--username" "myusername" "--app_identifier" "org.example.myapp" "--team_name" "My Team" "--ipa" "/Users/mickey/Desktop/tmp.ipa" "--skip_screenshots" "--skip_metadata" "--skip_app_version_update" "--force" "--platform" "ios"
```

Of course supporting the new App Store Connect API method that got added to fastlane recently would be very well appreciated but for now the simple change of making password a non-mandatory field would ease all the pain.

Btw, Apple has just announced that they will require 2FA for all users by february 2021 or so and this issue will affect even more bitrise users by then.

**Comment by godrei** [comment]
Hi @rovkinmax , @victormihaita and @zdurlan could you please try the latest version of the step with `fastlane version input = latest-stable` and share the build URL, if it fails?

In the latest version ([2.18.1](https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/releases/tag/2.18.1)) we improved the logging around Apple developer connection and added validation for the connection (proper connection, connected account, and app store apple id sync, expiry).

---

@knox you can use the `Deploy to iTunes Connect - Application Loader` step if you only need to upload a new version of your IPA (password is optional). 

The benefit of using this (Fastlane deliver) based step is the metadata and screenshot upload, for that username + password + FASTLANE_SESSION (+application-specific password for binary upload) is needed in the case of TFA enabled accounts.

https://docs.fastlane.tools/best-practices/continuous-integration/#application-specific-passwords:

Note: The application-specific password will not work if your action usage does anything else than uploading the binary, 
e.g. updating any metadata like setting release notes or distributing to testers, etc.

**Comment by knox** [comment]
@godrei i know the benefit of Deliver over Application Loader and that's why i'd prefer to use it.

> for that username + password + FASTLANE_SESSION (+application-specific password for binary upload) is needed

I think there is a missunderstanding of application specific passwords. They where ment to be a _substition_ for password + 2nd factor so one does not need to provide the actual password. But the configuration of this build step requires to provide _both_. I believe that this is wrong. And the worst thing is that even if both are configured the step still fails when 2FA is activated for the account given. 🤷 

I once tried to fix the configuration and use of application specific password as you can see [here](https://github.com/knox/steps-deploy-to-itunesconnect-deliver/commit/10066598b80d519c83ce263deaff726e17fac05b) but i did not finish it because application specific passwords are superseeded by API keys for quite a while.

For a proper solution supporting 2FA this step should be updated to support API keys just as the mentioned Application Loader step already does. Thanks.

**Comment by knox** [comment]
With #88 we now can forget about application specific passwords now and move on to use App Store Connect API Keys instead.

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just open a new issue!
